server:
  port: 8081
spring:
  application:
    name: customer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 30    #设置抓取信息的时间,默认30S
logging:
  level:
    com:
      netflex: debug