server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://slave2:8762/eureka/
spring:
  application:
    name: cloud-application
  profiles: slaveA

---
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://slave1:8761/eureka/
spring:
  application:
    name: cloud-application
  profiles: slaveB
