server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false   #自我保护
    eviction-interval-timer-in-ms: 5000  #单位ms 清理注册表的时间
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
